<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'eventsourcing\\application\\factory' => '/Application/Factory.php',
                'eventsourcing\\domain\\checkout' => '/Domain/Checkout.php',
                'eventsourcing\\domain\\eventsourced' => '/Domain/EventSourced.php',
                'eventsourcing\\event\\billingaddressdefinedevent' => '/Event/BillingAddressDefinedEvent.php',
                'eventsourcing\\event\\checkoutstartedevent' => '/Event/CheckoutStartedEvent.php',
                'eventsourcing\\event\\event' => '/Event/Event.php',
                'eventsourcing\\exception\\cartnotfoundexception' => '/Exception/CartNotFoundException.php',
                'eventsourcing\\infrastructure\\eventreader' => '/Infrastructure/EventReader.php',
                'eventsourcing\\infrastructure\\eventwriter' => '/Infrastructure/EventWriter.php',
                'eventsourcing\\infrastructure\\filesystemeventreader' => '/Infrastructure/FileSystemEventReader.php',
                'eventsourcing\\infrastructure\\filesystemeventwriter' => '/Infrastructure/FileSystemEventWriter.php',
                'eventsourcing\\listener\\checkoutcartdisplayupdater' => '/Listener/CheckoutCartDisplayUpdater.php',
                'eventsourcing\\listener\\eventdispatcher' => '/Listener/EventDispatcher.php',
                'eventsourcing\\listener\\eventlistener' => '/Listener/EventListener.php',
                'eventsourcing\\listener\\myfirsteventlistener' => '/Listener/MyFirstEventListener.php',
                'eventsourcing\\model\\billingaddress' => '/Model/BillingAddress.php',
                'eventsourcing\\model\\cartitem' => '/Model/CartItem.php',
                'eventsourcing\\model\\cartitemcollection' => '/Model/CartItemCollection.php',
                'eventsourcing\\model\\eventlog' => '/Model/EventLog.php',
                'eventsourcing\\model\\mail' => '/Model/Mail.php',
                'eventsourcing\\model\\sessionid' => '/Model/SessionId.php',
                'eventsourcing\\projector\\cartcheckoutdisplay' => '/Projector/CartCheckoutDisplay.php',
                'eventsourcing\\service\\cartservice' => '/Service/CartService.php',
                'eventsourcing\\service\\checkoutservice' => '/Service/CheckoutService.php',
                'eventsourcing\\service\\mailservice' => '/Service/MailService.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
